config:
  - name: "Sarpam CLI"
    path: "examples/sarpamcli/config.yaml"
    description: "Example of a Sarpam CLI configuration"
    tags: ["sarpam", "cli", "example"]
    parameters:
      - name: "input"
        type: "file"
        description: "Input file"
        required: true
      - name: "output"
        type: "file"
        description: "Output file"
        required: true
